### PR TITLE
First attempt at changing the classes to traits

### PR DESCRIPTION
**Pull request by EspadaV8**
I've tried to move all the code out of the classes and into traits.

The tests pass, which is good, but I've not got anything 'real' to test this with, so it would be nice if someone could try it with some real world data.

A few things need to remain the in class versions for backwards compatibility that can't go into the traits, which means if people use the trait version there will be a little bit more set up involved.

Let me know if you spot any issues with this

### CODE REVIEW

**Comment by EspadaV8** [comment]
Rebased on latest master

**Comment by EspadaV8** [comment]
Oops, I completely forgot to sort out the trait c'tor

**Comment by EspadaV8** [comment]
I think this is mostly there. All tests are passing locally for me and manually testing it seems to work too.

I can't work out why travis is failing, previous tests that passed are also failing so I'm wondering if it's something that's changed there.

**Comment by fuzzybaird** [comment]
How is this pull request coming @EspadaV8?

**Pull request closed without merging**
