### PR TITLE
Update Travis to test on Laravel 5.6 to 6.x

### PR DESCRIPTION
**Pull request by avvertix**
Looking at #222 I was questioning myself if everything is compatible with latest PHP and Laravel versions.

The main goal of this pull request is to ensure that automated tests on Travis CI can be executed for all the supported Laravel and PHP versions, so I did the following changes:

- Make PHP 7.0 the minimum PHP version
- Update composer.json to ensure a Laravel package is specified to mark the version under testing
- Update composer.json to ensure that the dev dependencies can be resolved to an installable set of packages for the supported PHP and Laravel version
- Update unit tests to remove deprecation notices

### CODE REVIEW

**Comment by franzose** [comment]
Hello, @avvertix! Thank you for your work. But I'm afraid it's going to conflict with the changes I have already made in another branch. Currently I'm working on ClosureTable 6.0, it'll have a lot of bugfixes and improvements, but still 5.6 compatible.

**Comment by franzose** [comment]
I think I'll try to incorporate some of your work into mine. Thank you and sorry for the inconvenience.

**Comment by avvertix** [comment]
Oh I didn't see the other branch, otherwise I might have started from it.

Feel free to grab what you need from this pull request.

**Comment by franzose** [comment]
> Oh I didn't see the other branch, otherwise I might have started from it.

This is because I haven't pushed it yet.

**Comment by franzose** [comment]
Hi, @avvertix! I really need your work on Travis CI configuration. Please, take a look at 6.x branch. It's a new branch in which I'm working on a new release. I'd highly appreciate your **new PR** into that branch.

Notice that ClosureTable 6 must support Laravel 5.4+ and PHP 5.6+ to provide maximum smoothness for the existing users during upgrade (I hope they exist 😀). I have already tested it manually on 5.4, 5.5 and 5.6. But, of course, we need an automatic way to check that.

Ensure to include Laravel 5.4-5.6, PHP 5.6-7.2 and PostgreSQL into Travis CI configuration file, okay?

**Comment by avvertix** [comment]
Ok I'll try to rebase on that branch and get it to work for Laravel 5.4 to 5.6.

**Comment by franzose** [comment]
@avvertix thank you, keep in mind that the only file needed is **.travis.yaml**.

**Comment by avvertix** [comment]
Sure, I will grab the 6.x branch and open a new pull request to keep it as clean as possible.

**Comment by franzose** [comment]
Closing in favour of #226

**Pull request closed without merging**
